_target_: src.models.cifar_module.CIFARLitModule

optimizer:
  _target_: torch.optim.SGD #torch.optim.Adam
  _partial_: true
  lr: 0.01585090974453875 #0.001
  weight_decay: 0.0

net:
  _target_: timm.create_model
  model_name: resnet18
  pretrained: True
  num_classes: 10
  #_target_: resnet18 #src.models.components.simple_dense_net.SimpleDenseNet
  #input_size: 3072 # 32x32*3
  #lin1_size: 256 #  hidden1 dims
  #lin2_size: 128 # hidden2 dims
  #lin3_size: 64 # hidden3 dims
  #output_size: 10 # output units
